### ISSUE TITLE
0 lag off

### ISSUE THREAD

**Issue by jswoboda** [jswoboda/RadarDataSim#4]
The test case yields a 0th lag that's off by an order of magnitude from what it should be for simple cases that I was looking at.

**Comment by jswoboda** [comment]
When checking the lags for long pulse also check the barker codes as well.

**Comment by jswoboda** [comment]
Fixed this issue with long pulse and barker pulse. Also it was found that the noise temperature for PFISR was about 360 K, which is 3x higher then it should be according to documentation. 

For the long pulse case the power matches well with an input phantom that has a constant Te, Ti ratio.

![comp0](https://cloud.githubusercontent.com/assets/2608303/7543362/bcf651e2-f591-11e4-827d-876f22d8cc7c.png)

The Barker code case is similar but there is an extra division by 4 in the code for doing the matched filtering and pulse integration. I'm not sure where this comes from but it lines up well with the electron density after this was fixed. The main issue with the barker code was that instead of integrating powers I was integrating IQ samples after the matched filtering which created. This yielded an estimate that was many orders of magnitude too high. Again using a similar phantom as with the long pulse, just using a electron density distribution from a Chapman function with different parameters, we get the following

![comp0](https://cloud.githubusercontent.com/assets/2608303/7543452/65192dcc-f592-11e4-87d4-7e21447fe337.png)

**Comment by jsemeter** [comment]
Hi John,

These results are very interesting.  A publication that describes the ISR simulator, and then demonstrates it’s utility in experiment design for dynamic ionosphere environments, is a strong idea.

Can you put together an end-to-end story, involving a bunch of figures and a narrative to explain what’s going on?    So like, the initial time-dependent modeled ionosphere (Ne, Te, Ti, V), sampling this ionosphere (maybe with different beam positions, different pulse patterns), fitting the simulated data for different integration periods.

If we can get to a simple case where knowledge of the line of site integrated density (the TEC) is known and used to constrain the fit could be of interest.

Touch base tomorrow?  I’m in all day, meetings off and on.
josh

On May 8, 2015, at 2:56 PM, John Swoboda <notifications@github.com<mailto:notifications@github.com>> wrote:

Closed #4https://github.com/jswoboda/RadarDataSim/issues/4.

**Comment by jswoboda** [comment]
Found the true problem why the barker code needed to be divided by 4. Instead of dividing each spectrum by its sum and then multiplying by the RCS and the number of points in the spectrum I was summing the squares of the spectrum and then taking the square root. This was incorrect and I will fix this with the need commit. 

For the long pulse case we can see a comparison of the lags

![comp0](https://cloud.githubusercontent.com/assets/2608303/7889763/843784a0-060f-11e5-9301-b928fe1602d3.png)

And for the barker we can see the following
![comp0](https://cloud.githubusercontent.com/assets/2608303/7889773/97953420-060f-11e5-9323-2562a3e1249d.png)
